sudo: required
services:
  - docker

before_install:
  - docker build -t btsao604/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true btsao604/react-test npm test

after_success:
  - docker build -t btsao604/ben-frontend ./frontend
  - docker build -t btsao604/ben-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push btsao604/ben-frontend
  - docker push btsao604/ben-nginx
